"""Initial revision brute force 4

Revision ID: 76bcc61190cb
Revises: e2412789c190
Create Date: 2024-06-06 14:21:00.298265

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '76bcc61190cb'
down_revision = 'e2412789c190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templateworkout',
    sa.Column('template_workout_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workout_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('template_workout_id')
    )
    op.create_table('templateexercise',
    sa.Column('template_exercise_id', sa.Integer(), nullable=False),
    sa.Column('template_workout_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('name_exercise', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('muscle_group', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['template_workout_id'], ['templateworkout.template_workout_id'], ),
    sa.PrimaryKeyConstraint('template_exercise_id')
    )
    op.create_table('workout',
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_workout_id', sa.Integer(), nullable=False),
    sa.Column('workout_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('records', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_workout_id'], ['templateworkout.template_workout_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('workout_id')
    )
    op.create_table('exercise',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('template_exercise_id', sa.Integer(), nullable=False),
    sa.Column('exercise_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('muscle_group', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['template_exercise_id'], ['templateexercise.template_exercise_id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.workout_id'], ),
    sa.PrimaryKeyConstraint('exercise_id')
    )
    op.create_table('set',
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('kg', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('type_rep', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.exercise_id'], ),
    sa.PrimaryKeyConstraint('set_id')
    )
    op.drop_table('item')
    op.add_column('user', sa.Column('number_of_workouts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'number_of_workouts')
    op.create_table('item',
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='item_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='item_pkey')
    )
    op.drop_table('set')
    op.drop_table('exercise')
    op.drop_table('workout')
    op.drop_table('templateexercise')
    op.drop_table('templateworkout')
    # ### end Alembic commands ###
