"""first upgrade after the brute force 4

Revision ID: b70fa8facee7
Revises: 76bcc61190cb
Create Date: 2024-06-06 14:24:10.512976

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b70fa8facee7'
down_revision = '76bcc61190cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
